Repository CachaSan10/TP_FINAL_2023-PV, pull requests merged in 2023-07, with the labels that each got.

#58 Responsable: VillenaFranco
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/GestionDatosController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/UsuarioController.java
  Tp_Final_Programacion_Visual_2023/src/main/resources/application.properties
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/autenticacion.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/contacto.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/gestion_datos.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/layouts/nav.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/usuarios.html
Labels: Modificar archivos, Crear archivos html, Fusion de ramas, Crear Controller

#60 Responsable: VillenaFranco
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/entity/Usuario.java
  Tp_Final_Programacion_Visual_2023/src/main/resources/application.properties
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/nuevo_usuario.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/usuarios.html
Labels: Modificar archivos

#62 Responsable: Moyata, Lautaro Nahuel
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/css/estilos.css
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/contacto.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/id-usuario-testimonio.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/layouts/footer.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/nuevo_testimonio.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/testimonio.html
Labels: Modificar archivos, Crear archivos html

#63 Responsable: Moyata, Lautaro Nahuel
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/layouts/footer.html
Labels: Modificar archivos

#64 Responsable: Nahuel Alberto Cachambi
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/IngredienteController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/RecetaController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/entity/Ingrediente.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/entity/Receta.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/imp/IngredienteServiceMysqlImp.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/imp/RecetaServiceMysqlImp.java
  Tp_Final_Programacion_Visual_2023/src/main/resources/messages.properties
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/gestion_datos.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/gestion_datos_ingrediente.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/gestion_datos_receta.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/nueva_receta.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/nuevo_ingrediente.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/receta.html
Labels: Modificar archivos, Crear archivos html, Fusion de ramas

#66 Responsable: Nahue Alberto Cachambi
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/GestionDatosController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/UsuarioController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/entity/Usuario.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/imp/UsuarioServiceMysqlImp.java
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/autenticacion.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/nuevo_usuario.html
Labels: Fusion de ramas

#68 Responsable: Moyata Lautaro Nahuel
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/TestimonioController.java
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/id-usuario-testimonio.html
Labels: Modificar archivos

#69 Responsable: Nahuel Alberto Cachambi
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/GestionDatosController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/IndiceMasaCorporalController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/entity/IndiceMasaCorporal.java
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/autenticacion.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/buscador-peso-ideal.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/calculadora-imc.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/registros-imc.html
Labels: Fusion de ramas

#71 Responsable: Moyata, Lautaro Nahuel
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/TestimonioController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/entity/Testimonio.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/imp/TestimonioServiceMysqlImp.java
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/gestion_dato_testimonio.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/gestion_datos.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/nuevo_testimonio.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/testimonio.html
Labels: Modificar archivos, Crear archivos html

#74 Responsable: VillenaFranco
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/entity/Receta.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/entity/Usuario.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/repository/IRecetaRepository.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/repository/IUsuarioRepository.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/imp/RecetaServiceMysqlImp.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/imp/UsuarioServiceMysqlImp.java
Labels: documentation, Modificar archivos, Documentar clase

#77 Cachambi vista controller(ingrediente,receta)
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/RecetaController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/entity/IndiceMasaCorporal.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/entity/Ingrediente.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/entity/Receta.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/IIndiceMasaCorporalService.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/IRecetaService.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/imp/IndiceMasaCorporalServiceMysqlImp.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/imp/IngredienteServiceMysqlImp.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/imp/RecetaServiceMysqlImp.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/util/UploadFile.java
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/images_upload/imagen.txt
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/nueva_receta.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/receta.html
Labels: Modificar archivos, Fusion de ramas, Documentar clase

#78 Responsable: Nahuel Alberto Cachambi
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/RecetaController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/entity/Receta.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/IRecetaService.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/imp/RecetaServiceMysqlImp.java
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/nueva_receta.html
Labels: Modificar archivos

#80 Responsable: Moyata, Lautaro Nahuel
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/TestimonioController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/entity/Testimonio.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/repository/ITestimonioRepository.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/ITestimonioService.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/imp/TestimonioServiceMysqlImp.java
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/gestion_dato_testimonio.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/gestion_datos.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/layouts/nav.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/nuevo_testimonio.html
Labels: Modificar archivos

#82 Responsable: VillenaFranco
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/imp/RecetaServiceMysqlImp.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/imp/UsuarioServiceMysqlImp.java
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/css/estilos.css
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/images/8971142.jpg
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/images/doctores.jpg
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/images/estable.png
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/images/im1.png
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/images/img322.png
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/images/prevencion-salud.png
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/images/salud.jpg
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/images/saludmental.jpg
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/images/tratamiento.jpg
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/images/vacunas.png
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/agradecimiento.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/index.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/layouts/header.html
Labels: Modificar archivos, Agregar Validaciones

#84 Responsable: VillenaFranco
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/css/estilos.css
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/index.html
Labels: Modificar archivos

#87 Responsable: Villena Franco
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/css/estilos.css
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/images/genetica.png
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/images/medicina3.jfif
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/images/medicinas.jpg
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/images/medicinas2.png
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/images/salud2.jpg
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/index.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/nuevo_usuario.html
Labels: Modificar archivos

#90 Responsable: Nahuel Alberto Cachambi
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/RecetaController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/entity/Ingrediente.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/entity/Receta.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/imp/RecetaServiceMysqlImp.java
  Tp_Final_Programacion_Visual_2023/src/main/resources/import.sql
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/images_upload/pescado.jpg
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/images_upload/ternera.png
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/layouts/recetas.html
Labels: Fusion de ramas

#92 Moyata vista
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/TestimonioController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/entity/Testimonio.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/repository/ITestimonioRepository.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/ITestimonioService.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/imp/TestimonioServiceMysqlImp.java
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/gestion_dato_testimonio.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/gestion_datos.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/id-usuario-testimonio.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/layouts/nav.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/nuevo_testimonio.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/testimonios.html
Labels: Modificar archivos

#94 Responsable: VillenaFranco
  .gitignore
  Tp_Final_Programacion_Visual_2023/src/main/resources/import.sql
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/css/estilos.css
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/index.html
Labels: Modificar archivos

#96 Responsable:Moyata Lautaro Nahuel
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/TestimonioController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/entity/Testimonio.java
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/layouts/nav.html
Labels: Modificar archivos

#97 Responsable: Moyata Lautaro Nahuel
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/entity/Testimonio.java
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/gestion_dato_testimonio.html
Labels: Modificar archivos

#99 Responsable: Villena Franco
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/css/estilos.css
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/images/8971142.jpg
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/index.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/usuarios.html
Labels: Modificar archivos

#100 Responsable: Nahuel Alberto Cachambi
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/IndiceMasaCorporalController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/repository/IIndiceMasaCorporalRepository.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/IIndiceMasaCorporalService.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/imp/IndiceMasaCorporalServiceMysqlImp.java
  Tp_Final_Programacion_Visual_2023/src/main/resources/import.sql
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/gestion_datos.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/gestion_datos_ingrediente.html
Labels: Modificar archivos, Crear archivos html, Fusion de ramas

#102 Responsable: Villena Franco
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/css/estilos.css
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/gestion_datos_imc.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/gestion_datos_ingrediente.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/gestion_datos_receta.html
Labels: Modificar archivos

#105 Responsable: Moyata Lautaro Nahuel
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/TestimonioController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/entity/Testimonio.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/ITestimonioService.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/imp/TestimonioServiceMysqlImp.java
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/css/estilos.css
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/id-usuario-testimonio.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/layouts/footer.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/nuevo_testimonio.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/testimonios.html
Labels: Modificar archivos

#106 Reponsable: Nahuel Alberto Cachambi
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/IndiceMasaCorporalController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/RecetaController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/repository/IIngredienteRepository.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/repository/IRecetaRepository.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/imp/RecetaServiceMysqlImp.java
  Tp_Final_Programacion_Visual_2023/src/main/resources/import.sql
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/css/estilos.css
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/calculadora-imc.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/gestion_datos_imc.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/nueva_receta.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/recetas.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/registros-imc.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/resultado-imc.html
Labels: Modificar archivos

#107 Responsable: Moyata Lautaro Nahuel
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/imp/TestimonioServiceMysqlImp.java
Labels: Modificar archivos

#109 Responsable: Villena Franco
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/IngredienteController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/entity/Ingrediente.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/entity/Receta.java
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/css/estilos.css
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/nuevo_ingrediente.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/usuarios.html
Labels: Modificar archivos

#110 Responsable: Nahuel Alberto Cachambi
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/IngredienteController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/RecetaController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/entity/Ingrediente.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/entity/Receta.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/IRecetaService.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/imp/RecetaServiceMysqlImp.java
  Tp_Final_Programacion_Visual_2023/src/main/resources/import.sql
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/images_upload/imagen.txt
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/nueva_receta.html
Labels: Modificar archivos

#114 Responsable: Moyata Lautaro Nahuel
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/TestimonioController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/imp/TestimonioServiceMysqlImp.java
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/gestion_dato_testimonio.html
Labels: Modificar archivos

#115 Responsable: Moyata, Lautaro Nahuel
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/imp/TestimonioServiceMysqlImp.java
Labels: Modificar archivos

#118 Responsable: Moyata, Lautaro Nahuel
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/TestimonioController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/entity/Testimonio.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/repository/ITestimonioRepository.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/ITestimonioService.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/imp/TestimonioServiceMysqlImp.java
  Tp_Final_Programacion_Visual_2023/src/main/resources/import.sql
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/css/estilos.css
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/index.html
Labels: Modificar archivos, Documentar clase

#119 Cachambi modificar indice masa corporal
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/IndiceMasaCorporalController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/TestimonioController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/entity/IndiceMasaCorporal.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/entity/Testimonio.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/IIndiceMasaCorporalService.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/imp/IndiceMasaCorporalServiceMysqlImp.java
  Tp_Final_Programacion_Visual_2023/src/main/resources/import.sql
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/buscador-peso-ideal.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/calculadora-imc.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/gestion_datos_imc.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/nuevo_testimonio.html
Labels: Modificar archivos, Fusion de ramas

#120 Responsable: Nahuel Alberto Cachambi
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/GestionDatosController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/IndiceMasaCorporalController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/IngredienteController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/repository/IIndiceMasaCorporalRepository.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/repository/ITestimonioRepository.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/service/imp/TestimonioServiceMysqlImp.java
Labels: Modificar archivos, Fusion de ramas, Documentar clase

#122 Responsable: Villena Franco
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/UsuarioController.java
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/gestion_dato_testimonio.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/nuevo_testimonio.html
Labels: Modificar archivos

#124 Responsable: Villena Franco
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/index.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/recetas.html
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/testimonios.html
Labels: Modificar archivos, Fusion de ramas

#126 Responsable: Moyata, Lautaro Nahuel
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/ContactoController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/IndexController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/controller/RecetaController.java
  Tp_Final_Programacion_Visual_2023/src/main/java/ar/edu/unju/fi/repository/IIngredienteRepository.java
  Tp_Final_Programacion_Visual_2023/src/main/resources/static/css/estilos.css
  Tp_Final_Programacion_Visual_2023/src/main/resources/templates/index.html
Labels: Documentar clase
